[package]
name = "bitbar-derive"
version = "0.7.2"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"
description = "Proc-macros for the bitbar crate"
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fenhl/rust-bitbar"

[lib]
proc-macro = true

[features]
tokio = []
tokio02 = []

[dependencies]
proc-macro2 = "1"
quote = "1"

[dependencies.syn]
version = "1"
features = ["full"]
